### PR TITLE
Keep coherent version numbers (package.json <> bower.json)

### PR DESCRIPTION
**Pull request by llambeau**
It would be interesting to keep version coherent between the official version, the NPM package and the Bower package.

Could you merge this pull request and create a new tag for this version?

Cheers!
LL

### CODE REVIEW

**Comment by ryanbillingsley** [comment]
I see no problem with this :+1:

**Comment by llambeau** [comment]
Could you tag the project as well please?
Thanks

**Comment by ryanbillingsley** [comment]
@llambeau done

**Comment by llambeau** [comment]
Thanks

**Pull request merged**
